### ISSUE TITLE
Error with Office365CardFormatter

### ISSUE THREAD

**Issue by pintman** [AnesFoufa/python-teams-logger#15]
I get the following error when configuring the teams-logger within a flask application using the ini-config.

    TypeError: Office365CardFormatter.__init__() takes 2 positional arguments but 4 were given

This is the config file that I am using.

```
[loggers]
keys=root

[handlers]
keys=msteams

[formatters]
keys=mscardformatter

[logger_root]
level=DEBUG
handlers=msteams

[handler_msteams]
class=teams_logger.TeamsQueueHandler
formatter=mscardformatter
args=('https://....', )

[formatter_mscardformatter]
class=teams_logger.Office365CardFormatter
#args=(["name", "levelname", "lineno"], )
kwargs = {'facts': ["name", "levelname", "lineno"]}
```

Any ideas?

**Comment by AnesFoufa** [comment]
Hi. I'm trying to reproduce the bug.

**Comment by AnesFoufa** [comment]
The formatter initialization from a config file doesn't support custom arguments in args and kwargs
https://docs.python.org/3/library/configparser.html
I suggest you initialize the formatter from a dictionary.
I'll try to build an initialization API that's more compatible with Python logging standards in version 1.

**Comment by pintman** [comment]
Thanks for that information. It would be great to be able to init the formatter from an ini config file.

**Comment by pintman** [comment]
I assume initializing a formatter from a dictionary doesn't support custom arguments either.

https://docs.python.org/3/library/logging.config.html#logging-config-dictschema

Except you create a user-defined object and a factory.

**Comment by AnesFoufa** [comment]
This works fine:
```
import logging.config
import logging
dict_config = {
    'version': 1,
    "loggers": {
        "": {
            "level": "INFO",
            "handlers": ["msteams"]
        },
    },
    "handlers": {
            "msteams": {
                "class": "teams_logger.TeamsQueueHandler",
                "url": 'https://....',
                "formatter": "mscardformatter"
            }
        },
        "formatters": {
            "mscardformatter": {
                "()": "teams_logger.Office365CardFormatter",
                "facts": ["name", "levelname"]
            }
        }
}
logging.config.dictConfig(dict_config)
root_logger = logging.getLogger()
print(root_logger.handlers[0].formatter.facts)
# prints {'name', 'levelname'}
```
You can also initialize from a yaml file.

**Comment by pintman** [comment]
Thanks for your great support. I will try this out. :D
